### ISSUE TITLE
Change scientific_name and taxon_id of blanks

### ISSUE THREAD

**Issue by josenavas** [biocore/labadmin#49]
EBI no longer allows us to submit the blanks as unclassified metagenome. We need to modify the pulldown to change the values of taxon_id and scientific_name. The new values are:
  - TAXON_ID: `449393`
  - SCIENTIFIC_NAME: `freshwater metagenome`

@squirrelo can you fix this before the next AG round is ready? I'm fixing it in Qiita directly right now for the current round.

**Comment by antgonza** [comment]
Is it? I'm not sure BLANKs are freshwater ...

**Comment by squirrelo** [comment]
This is from @ackermag. They are.

**Comment by ackermag** [comment]
Explanation - there is no specific classification for blanks.  In the past I used 408169 (metagenomes) but EBI no longer accepts this.  Now use freshwater (note sp) metagenome (449393) because essentially sterile water is made from freshwater. Plan to ask NCBI for a more suitable category.

**Comment by rob-knight** [comment]
That is really going to annoy people who actually study freshwater, to put
it mildly.

Rob Finn is here for 2 days for workshop I am running, added to cc for
advice...

On Mar 15, 2016, at 10:08 AM, Gail Ackermann <notifications@github.com>
wrote:

Explanation - there is no specific classification for blanks. In the past I
used 408169 (metagenomes) but EBI no longer accepts this. Now use
freshwater (note sp) metagenome (449393) because essentially sterile water
is made from freshwater. Plan to ask NCBI for a more suitable category.

**Comment by rob-knight** [comment]
Trying to read between the lines, but it is not clear why EBI/ENA is not accepting metagenomes as sample classification.  Happy to discuss issues.

Rob


> On 15 Mar 2016, at 11:05, Rob Knight <rob@biota.com> wrote:
> 
> That is really going to annoy people who actually study freshwater, to put it mildly.
> 
> Rob Finn is here for 2 days for workshop I am running, added to cc for advice...
> 
> On Mar 15, 2016, at 10:08 AM, Gail Ackermann <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
>> Explanation - there is no specific classification for blanks. In the past I used 408169 (metagenomes) but EBI no longer accepts this. Now use freshwater (note sp) metagenome (449393) because essentially sterile water is made from freshwater. Plan to ask NCBI for a more suitable category.
>> 
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/biocore/labadmin/issues/49#issuecomment-196926702 <https://github.com/biocore/labadmin/issues/49#issuecomment-196926702>

--
-------------------------------------------------------------
Rob Finn 
Protein Families Team Leader
European Bioinformatics Institute (EMBL-EBI)
Tel: +44 1223 492679

**Comment by rob-knight** [comment]
Any idea why the orig taxon id below no longer ok?

On Mar 15, 2016, at 11:12 AM, Rob Finn <rdf@ebi.ac.uk> wrote:

Trying to read between the lines, but it is not clear why EBI/ENA is not
accepting metagenomes as sample classification.  Happy to discuss issues.

Rob


On 15 Mar 2016, at 11:05, Rob Knight <rob@biota.com> wrote:

That is really going to annoy people who actually study freshwater, to put
it mildly.

Rob Finn is here for 2 days for workshop I am running, added to cc for
advice...

On Mar 15, 2016, at 10:08 AM, Gail Ackermann <notifications@github.com>
wrote:

Explanation - there is no specific classification for blanks. In the past I
used 408169 (metagenomes) but EBI no longer accepts this. Now use
freshwater (note sp) metagenome (449393) because essentially sterile water
is made from freshwater. Plan to ask NCBI for a more suitable category.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/biocore/labadmin/issues/49#issuecomment-196926702


--
-------------------------------------------------------------
Rob Finn
Protein Families Team Leader
European Bioinformatics Institute (EMBL-EBI)
Tel: +44 1223 492679

**Comment by antgonza** [comment]
Will send them an email and double check. Note that EBI-metagenomics is different than EBI-ENA.

**Comment by ackermag** [comment]
I tried to contact NCBI...

On Tue, Mar 15, 2016 at 11:15 AM, Antonio Gonzalez <notifications@github.com
> wrote:

> Will send them an email and double check. Note that EBI-metagenomics is
> different than EBI-ENA.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/labadmin/issues/49#issuecomment-196956740>
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by squirrelo** [comment]
Fixed in #64
